#include <stddef.h>
#include <stdint.h>

const uint8_t g_lua_script[] =
"-- Record 5 BME280 measurements, one per second\n"
"device.log(\"Lua runner started\")\n"
"\n"
"for i = 1, 5 do\n"
"    local env, env_err = device.read_env()\n"
"    if env then\n"
"        local ts = device.read_rtc() or 0\n"
"        local id_t = db.next_id()\n"
"        local id_h = db.next_id()\n"
"        local id_p = db.next_id()\n"
"        local records = {\n"
"            { sensor_id=1, measure_id=id_t, measure_type=\"temperature\",\n"
"              timestamp=ts, data_type=\"float\", value=env.temperature_c },\n"
"            { sensor_id=1, measure_id=id_h, measure_type=\"humidity\",\n"
"              timestamp=ts, data_type=\"float\", value=env.humidity_pct },\n"
"            { sensor_id=1, measure_id=id_p, measure_type=\"pressure\",\n"
"              timestamp=ts, data_type=\"float\", value=env.pressure_pa },\n"
"        }\n"
"        local ok, err = db.store(records)\n"
"        if ok then\n"
"            device.log(string.format(\"Stored reading %d: T=%.2fC H=%.1f%% P=%.0fPa\",\n"
"                i, env.temperature_c, env.humidity_pct, env.pressure_pa))\n"
"        else\n"
"            device.log(\"Store failed: \" .. (err or \"unknown\"))\n"
"        end\n"
"    else\n"
"        device.log(\"Env read failed: \" .. (env_err or \"unknown\"))\n"
"    end\n"
"    if i < 5 then device.sleep_ms(1000) end\n"
"end\n"
"\n"
"local cnt = db.count(\"temperature\")\n"
"device.log(\"Total temperature records: \" .. tostring(cnt))\n"
"device.log(\"Done\")\n";

const size_t g_lua_script_len = sizeof(g_lua_script) - 1;
